### ISSUE TITLE
AimRobot.Api.events.ev.PlayerDeathEvent定义

### ISSUE THREAD

**Issue by 1508425541zhang** [H4rry217/AimRobotLite#2]
1. public string killerName;

1. 是击杀者还是被击杀者

1.   public string killerBy;

2.   public string playerPlatoon;

3.   public string playerName;

这三个又是什么定义，
希望能帮我解答，谢谢

**Comment by H4rry217** [comment]
1、killerName 击杀者
2、killerBy 击杀方式
3、playerPlatoon 被击杀者的战排
4、playerName 被击杀者名字
